sudo: false

services:
  - docker

script:
  - docker-compose build app
  - docker-composer run --rm app composer ci

after_success:
  - docker images

after_error:
  - docker-compose logs

after_failure:
  - docker-compose logs

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
